apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: second-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kregq/kustomize.git
    targetRevision: main
    path: 01-working-with-kustomize/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: kapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
