apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namePrefix: production-
namespace: second-app-production

images:
- name: quay.io/redhatworkshops/welcome-php
  newTag: v1.0.0

commonLabels:
  app.kubernetes.io/environment: production
